<a href="https://colab.research.google.com/github/Deeptanshu-Paul/SWYNEX-Data-Preparation/blob/main/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np
train = pd.read_csv('Training.csv')
test = pd.read_csv('Testing.csv')

In [30]:
print(train.shape)

(4920, 134)

In [31]:
print(test.shape)

(42, 133)

In [32]:
train.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,Unnamed: 133
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN

In [33]:
train.dtypes.value_counts()

int64      132
object       1
float64      1
Name: count, dtype: int64

In [34]:
set(train.columns) - set(test.columns)

{'Unnamed: 133'}

In [35]:
print(train.isnull().sum().sum())

4920

In [36]:
print(test.isnull().sum().sum())

0

In [37]:
print(train.duplicated().sum())

4616

In [38]:
print(len(train))

4920

In [39]:
phantom_cols = [c for c in train.columns if c.startswith("Unnamed:")]
print(phantom_cols)

['Unnamed: 133']

In [40]:
train = train.drop(columns=phantom_cols)

In [41]:
print(train.shape)

(4920, 133)

In [42]:
def clean_col(c):
    return c.strip().replace(" ", "_")

In [43]:
train.columns = [clean_col(c) for c in train.columns]
test.columns = [clean_col(c) for c in test.columns]

In [44]:
print(list(train.columns) == list(test.columns))

True

In [45]:
train["prognosis"].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [46]:
train["prognosis"] = train["prognosis"].str.strip()
test["prognosis"] = test["prognosis"].str.strip()

In [47]:
print(train["prognosis"].nunique())

41

In [48]:
symptom_cols = [c for c in train.columns if c != "prognosis"]

In [49]:
for c in symptom_cols:
    assert set(train[c].unique()) <= {0, 1}, f"{c} is not binary!"

In [50]:
train[symptom_cols] = train[symptom_cols].astype("int8")
test[symptom_cols] = test[symptom_cols].astype("int8")

In [51]:
train["prognosis"] = train["prognosis"].astype("category")
test["prognosis"] = test["prognosis"].astype("category")

In [52]:
train.dtypes.value_counts()

int8        132
category      1
Name: count, dtype: int64

In [53]:
n_dupes = train.duplicated().sum()
print(n_dupes, "/", len(train))

4616 / 4920

In [54]:
train.groupby("prognosis", observed=True)[symptom_cols].apply(lambda g: g.drop_duplicates().shape[0])

prognosis
(vertigo) Paroymsal  Positional Vertigo     7
AIDS                                        5
Acne                                        5
Alcoholic hepatitis                         8
Allergy                                     5
Arthritis                                   6
Bronchial Asthma                            7
Cervical spondylosis                        6
Chicken pox                                10
Chronic cholestasis                         8
Common Cold                                 9
Dengue                                     10
Diabetes                                    9
Dimorphic hemmorhoids(piles)                6
Drug Reaction                               6
Fungal infection                            5
GERD                                        7
Gastroenteritis                             5
Heart attack                                5
Hepatitis B                                 9
Hepatitis C                                 7
Hepatitis D                                10
Hepatitis E                                 9
Hypertension                                6
Hyperthyroidism                             9
Hypoglycemia                                9
Hypothyroidism                              8
Impetigo                                    6
Jaundice                                    9
Malaria                                     8
Migraine                                   10
Osteoarthristis                             7
Paralysis (brain hemorrhage)                5
Peptic ulcer diseae                         7
Pneumonia                                   9
Psoriasis                                   7
Tuberculosis                                9
Typhoid                                     9
Urinary tract infection                     5
Varicose veins                              8
hepatitis A                                 9
dtype: int64

In [55]:
train.to_csv("Training_clean.csv", index=False)
test.to_csv("Testing_clean.csv", index=False)

print("Saved.")

Saved.